### ISSUE TITLE
Add details to implement dry run and formatting style in README

### ISSUE THREAD

**Issue by gwaygenomics** [WayScience/CytoPipe#4]
in #1 @axiomcura noted that his PR failed a `dry run` test. He also noted that he used `smkfmt` to autoformat the snakemake files. (Details in https://github.com/WayScience/CytoPipe/pull/1#issuecomment-1099470710).

@axiomcura, in a future PR, can you add these details to the README?

**Comment by axiomcura** [comment]
config implementation  and documentation have been merged!   PR:  #5
